path: /home/anwar/Documents/Vision/datasets/yolo_flora_cls
train: train
val: val

# 33 classes
names:
  0: acacia_dry
  1: acacia_not_dry
  2: adansonia_dry
  3: adansonia_not_dry
  4: aloe_dry
  5: aloe_not_dry
  6: andropogon_dry
  7: andropogon_not_dry
  8: baobab_dry
  9: baobab_not_dry
  10: brachystegia_dry
  11: brachystegia_not_dry
  12: colophospermum_dry
  13: colophospermum_not_dry
  14: combretum_dry
  15: combretum_not_dry
  16: erica_dry
  17: erica_not_dry
  18: euphorbia_dry
  19: euphorbia_not_dry
  20: ficus_dry
  21: ficus_not_dry
  22: khaya_dry
  23: khaya_not_dry
  24: macaranga_dry
  25: macaranga_not_dry
  26: protea_not_dry
  27: senegalia_dry
  28: senegalia_not_dry
  29: tamarix_dry
  30: tamarix_not_dry
  31: themeda_dry
  32: themeda_not_dry
