#!/usr/bin/env python3
"""
Flora Dataset: Detection → Classification Converter
=====================================================
Converts the broken YOLO detection dataset (all full-frame bboxes)
into an ImageNet-style classification folder structure that works
with `yolo classify train`.

Input layout (current):
    datasets/yolo_flora/
    ├── images/{train,val}/<species>_<id>.jpg
    └── labels/{train,val}/<species>_<id>.txt  (contains: <class_id> 0.5 0.5 1.0 1.0)

Output layout (new):
    datasets/yolo_flora_cls/
    ├── train/
    │   ├── acacia_not_dry/
    │   │   └── acacia_12345.jpg
    │   └── ...
    └── val/
        └── ...

Usage:
    python convert_to_classification.py              # Convert using symlinks (fast, saves disk)
    python convert_to_classification.py --copy       # Convert using file copies
    python convert_to_classification.py --dry-run    # Preview without changes
    python convert_to_classification.py --min-samples 20  # Drop classes with < 20 samples
"""

import argparse
import os
import shutil
import sys
from collections import defaultdict
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────
# Configuration — class mapping must match what the annotation script used
# ──────────────────────────────────────────────────────────────────────

# This is the mapping generated by 01_acquire_and_annotate.py (alphabetical order)
# It matches flora_data.yaml. The Kaggle run used data.yaml with a different ordering,
# but the LABEL FILES were written using THIS mapping.
CLASS_ID_TO_NAME = {
    0: "acacia_not_dry",
    1: "acacia_dry",
    2: "adansonia_not_dry",
    3: "adansonia_dry",
    4: "aloe_not_dry",
    5: "aloe_dry",
    6: "andropogon_not_dry",
    7: "andropogon_dry",
    8: "baobab_not_dry",
    9: "baobab_dry",
    10: "brachystegia_not_dry",
    11: "brachystegia_dry",
    12: "colophospermum_not_dry",
    13: "colophospermum_dry",
    14: "combretum_not_dry",
    15: "combretum_dry",
    16: "erica_not_dry",
    17: "erica_dry",
    18: "euphorbia_not_dry",
    19: "euphorbia_dry",
    20: "ficus_not_dry",
    21: "ficus_dry",
    22: "khaya_not_dry",
    23: "khaya_dry",
    24: "macaranga_not_dry",
    25: "macaranga_dry",
    26: "protea_not_dry",
    27: "protea_dry",
    28: "senegalia_not_dry",
    29: "senegalia_dry",
    30: "tamarix_not_dry",
    31: "tamarix_dry",
    32: "themeda_not_dry",
    33: "themeda_dry",
    34: "vachellia_not_dry",
    35: "vachellia_dry",
}

DATASET_ROOT = Path(__file__).parent / "datasets" / "yolo_flora"
OUTPUT_ROOT = Path(__file__).parent / "datasets" / "yolo_flora_cls"


def parse_label_file(label_path: Path) -> int | None:
    """Read a YOLO label file and return the class ID."""
    try:
        text = label_path.read_text().strip()
        if not text:
            return None
        # Take the first annotation line
        first_line = text.split("\n")[0]
        class_id = int(first_line.split()[0])
        return class_id
    except (ValueError, IndexError, OSError):
        return None


def convert_dataset(
    use_copy: bool = False,
    dry_run: bool = False,
    min_samples: int = 0,
):
    """Convert detection dataset to classification folder structure."""
    print("=" * 65)
    print("  Flora Dataset → Classification Converter")
    print("=" * 65)
    print(f"  Input  : {DATASET_ROOT}")
    print(f"  Output : {OUTPUT_ROOT}")
    print(f"  Mode   : {'COPY' if use_copy else 'SYMLINK'}")
    print(f"  Dry run: {dry_run}")
    print(f"  Min samples per class: {min_samples}")
    print("=" * 65)

    # ── Pass 1: Scan all label files and build class→image mapping ──
    class_images: dict[str, list[tuple[Path, str]]] = defaultdict(list)
    orphaned_images = 0
    missing_labels = 0
    unknown_class_ids = 0

    for split in ("train", "val"):
        img_dir = DATASET_ROOT / "images" / split
        lbl_dir = DATASET_ROOT / "labels" / split

        if not img_dir.exists():
            print(f"\n⚠️  {img_dir} does not exist, skipping")
            continue

        image_files = sorted(img_dir.glob("*"))
        print(f"\n📂 Scanning {split}: {len(image_files)} files...")

        for img_path in image_files:
            if img_path.suffix.lower() not in {".jpg", ".jpeg", ".png", ".webp"}:
                continue

            # Find matching label
            label_path = lbl_dir / (img_path.stem + ".txt")
            if not label_path.exists():
                missing_labels += 1
                continue

            class_id = parse_label_file(label_path)
            if class_id is None:
                orphaned_images += 1
                continue

            class_name = CLASS_ID_TO_NAME.get(class_id)
            if class_name is None:
                unknown_class_ids += 1
                continue

            class_images[f"{split}/{class_name}"].append((img_path, split))

    # ── Report class distribution ──
    print("\n" + "=" * 65)
    print("  CLASS DISTRIBUTION")
    print("=" * 65)

    # Aggregate by class name across splits
    class_totals: dict[str, int] = defaultdict(int)
    for key, imgs in class_images.items():
        split, class_name = key.split("/", 1)
        class_totals[class_name] += len(imgs)

    dropped_classes = set()
    for class_name in sorted(class_totals, key=lambda x: class_totals[x], reverse=True):
        count = class_totals[class_name]
        marker = ""
        if count < min_samples:
            marker = " ← DROPPING (below minimum)"
            dropped_classes.add(class_name)
        print(f"  {class_name:30s} : {count:>5,}{marker}")

    print(f"\n  Missing labels : {missing_labels}")
    print(f"  Orphaned images: {orphaned_images}")
    print(f"  Unknown class IDs: {unknown_class_ids}")

    if dropped_classes:
        print(f"\n  🗑️  Dropping {len(dropped_classes)} classes with < {min_samples} samples:")
        for c in sorted(dropped_classes):
            print(f"     - {c} ({class_totals[c]} samples)")

    # ── Pass 2: Create output structure ──
    if dry_run:
        print("\n💡 Dry run — no files created.")
        return

    total_linked = 0
    for key, images in sorted(class_images.items()):
        split, class_name = key.split("/", 1)

        if class_name in dropped_classes:
            continue

        out_dir = OUTPUT_ROOT / split / class_name
        out_dir.mkdir(parents=True, exist_ok=True)

        for img_path, _ in images:
            dest = out_dir / img_path.name
            if dest.exists():
                total_linked += 1
                continue

            if use_copy:
                shutil.copy2(img_path, dest)
            else:
                # Use absolute symlinks so they work everywhere
                os.symlink(img_path.resolve(), dest)

            total_linked += 1

    # ── Write the new data.yaml for classification ──
    # For yolo classify, data.yaml just needs the path
    kept_classes = sorted(
        [c for c in class_totals if c not in dropped_classes],
    )

    yaml_path = Path(__file__).parent / "flora_cls_data.yaml"
    with open(yaml_path, "w") as f:
        f.write(f"path: {OUTPUT_ROOT.resolve()}\n")
        f.write("train: train\n")
        f.write("val: val\n")
        f.write(f"\n# {len(kept_classes)} classes\n")
        f.write("names:\n")
        for i, name in enumerate(kept_classes):
            f.write(f"  {i}: {name}\n")

    print(f"\n✅ Conversion complete!")
    print(f"   Images linked/copied: {total_linked:,}")
    print(f"   Classes kept: {len(kept_classes)}")
    print(f"   Output: {OUTPUT_ROOT}")
    print(f"   Config: {yaml_path}")
    print(f"\n   Next steps:")
    print(f"   1. Verify:  ls -la {OUTPUT_ROOT}/train/ | head -20")
    print(f"   2. Zip:     cd datasets && zip -ry ../yolo_flora_cls.zip yolo_flora_cls/")
    print(f"   3. Upload to Kaggle and train with the new script")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert YOLO detection dataset to classification format"
    )
    parser.add_argument(
        "--copy", action="store_true",
        help="Copy files instead of creating symlinks"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Preview conversion without creating files"
    )
    parser.add_argument(
        "--min-samples", type=int, default=20,
        help="Drop classes with fewer than this many total samples (default: 20)"
    )
    args = parser.parse_args()

    convert_dataset(
        use_copy=args.copy,
        dry_run=args.dry_run,
        min_samples=args.min_samples,
    )
